language: python
python:
    - "3.5"
    - "3.6"
env:
    - DJANGO=2.2
install:
    - pip install pipenv
    - pipenv install --dev --system
script:
    - python runtests.py
after_success:
    - coveralls